package nomad.sbt

import sbt._
import sbt.Keys._
import sbt.complete.DefaultParsers._

import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/** Classloader that checks its own URLs before delegating to the parent.
  * This avoids conflicts between sbt's Scala 2.12 runtime and the user's Scala 3 runtime.
  */
private class ChildFirstClassLoader(urls: Array[java.net.URL], parent: ClassLoader)
  extends java.net.URLClassLoader(urls, parent) {

  override def loadClass(name: String, resolve: Boolean): Class[_] = {
    // JDK classes must always come from the parent
    if (name.startsWith("java.") || name.startsWith("javax.") || name.startsWith("sun.") || name.startsWith("jdk.")) {
      return super.loadClass(name, resolve)
    }
    // Try to find in our own URLs first
    try {
      val c = findClass(name)
      if (resolve) resolveClass(c)
      c
    } catch {
      case _: ClassNotFoundException =>
        super.loadClass(name, resolve)
    }
  }
}

/** Handles reading and rewriting the Scala manifest file to add new migration entries.
  *
  * Parses the manifest source to locate the `Vector(...)` block, determines the indentation
  * style from existing entries, and inserts new `SQLMigration(...)` lines while preserving
  * formatting and trailing commas.
  */
private object ManifestEditor {

  // Keep this rewriter in sync with the manifest shape generated by nomadInit.
  // If the expected Vector(...) style or migration entry conventions change,
  // revisit this logic and the scripted tests.
  private val VectorStartLine = """^(\s*)(?:.*=\s*)?Vector\(\s*$""".r

  /** Locates the Vector block boundaries and indentation within the manifest source. */
  private case class VectorBlock(
    startLine: Int,
    endLine: Int,
    entryIndent: String
  )

  /** Inserts one or more `SQLMigration("...")` entries into the manifest's Vector block.
    *
    * @param content the full manifest source file content
    * @param resourcePaths the classpath-relative paths to add
    * @return Right with the updated content, or Left with an error message
    */
  def addSqlMigrations(content: String, resourcePaths: Seq[String]): Either[String, String] = {
    if (resourcePaths.isEmpty) {
      Right(content)
    } else {
      val lines = content.linesIterator.toVector
      findVectorBlock(lines) match {
        case None =>
          Left("Could not find a supported migrations Vector(...) block in manifest file. Please add the migration manually.")
        case Some(block) =>
          val normalizedLines = ensureTrailingCommaBeforeClose(lines, block)
          val insertedLines = resourcePaths.map(path => s"""${block.entryIndent}SQLMigration("$path"),""")
          val updatedLines = ensureSqlMigrationImport(normalizedLines.patch(block.endLine, insertedLines, 0))
          Right(updatedLines.mkString("", "\n", "\n"))
      }
    }
  }

  private def ensureSqlMigrationImport(lines: Vector[String]): Vector[String] = {
    if (lines.exists(isSqlMigrationImport)) {
      lines
    } else {
      val lastNomadImport = lines.lastIndexWhere(_.trim.startsWith("import nomad"))
      val importLine = "import nomad.SQLMigration"
      if (lastNomadImport >= 0) lines.patch(lastNomadImport + 1, Vector(importLine), 0)
      else importLine +: lines
    }
  }

  private def isSqlMigrationImport(line: String): Boolean = {
    val trimmed = line.trim
    trimmed.startsWith("import ") &&
    trimmed.contains("nomad") &&
    trimmed.contains("SQLMigration")
  }

  private def findVectorBlock(lines: Vector[String]): Option[VectorBlock] = {
    lines.indices.reverseIterator.collectFirst(Function.unlift { idx =>
      lines(idx) match {
        case VectorStartLine(indent) =>
          findVectorEnd(lines, idx).map { endLine =>
            val existingEntryIndent = (idx + 1 until endLine).reverseIterator
              .map(lines)
              .map(_.takeWhile(_.isWhitespace))
              .find(_.nonEmpty)
            VectorBlock(
              startLine = idx,
              endLine = endLine,
              entryIndent = existingEntryIndent.getOrElse(indent + "  ")
            )
          }
        case _ =>
          None
      }
    })
  }

  private def findVectorEnd(lines: Vector[String], startLine: Int): Option[Int] = {
    var depth = parenDelta(lines(startLine))
    var idx = startLine + 1
    while (idx < lines.size) {
      depth += parenDelta(lines(idx))
      if (depth == 0) {
        return Some(idx)
      }
      idx += 1
    }
    None
  }

  private def parenDelta(line: String): Int =
    line.count(_ == '(') - line.count(_ == ')')

  private def ensureTrailingCommaBeforeClose(lines: Vector[String], block: VectorBlock): Vector[String] = {
    val previousEntryLine = (block.startLine + 1 until block.endLine).reverseIterator.find { idx =>
      val trimmed = lines(idx).trim
      trimmed.nonEmpty && !trimmed.startsWith("//")
    }

    previousEntryLine match {
      case Some(idx) if shouldAddTrailingComma(lines(idx).trim) =>
        lines.updated(idx, lines(idx) + ",")
      case _ =>
        lines
    }
  }

  private def shouldAddTrailingComma(trimmed: String): Boolean = {
    !trimmed.endsWith(",") &&
    !trimmed.endsWith("(") &&
    !trimmed.endsWith("{")
  }
}

/** Manages synchronization of migration SQL file patterns into GraalVM's `resource-config.json`.
  *
  * Ensures that migration SQL files are included as resources in native image builds by
  * adding (or creating) the appropriate include pattern in the resource configuration.
  */
private object GraalSync {

  /** Adds the migration resource pattern to the GraalVM resource config file, creating it if necessary.
    *
    * @param configFile the resource-config.json file
    * @param migrationsSubdir the migrations directory name to match (e.g., "migrations")
    * @param log sbt logger for progress messages
    */
  def syncResourceConfig(configFile: File, migrationsSubdir: String, log: sbt.util.Logger): Unit = {
    val pattern = s"$migrationsSubdir/.*\\\\.sql"
    if (configFile.exists()) {
      val content = IO.read(configFile)
      if (!content.contains(pattern)) {
        // Insert our pattern into the existing includes array
        val includesEnd = content.lastIndexOf("]")
        if (includesEnd >= 0) {
          val beforeBracket = content.substring(0, includesEnd).trim
          val needsComma = if (beforeBracket.endsWith("}")) "," else ""
          val entry =
            s"""|$needsComma
                |      {
                |        "pattern": "$pattern"
                |      }
                |    """.stripMargin
          val updated = content.substring(0, includesEnd).replaceAll("\\s+$", "") + entry + content.substring(includesEnd)
          IO.write(configFile, updated)
          log.info(s"Added migration resource pattern to: ${configFile.getName}")
        }
      }
    } else {
      val content =
        s"""|{
            |  "resources": {
            |    "includes": [
            |      {
            |        "pattern": "$pattern"
            |      }
            |    ]
            |  }
            |}
            |""".stripMargin
      IO.createDirectory(configFile.getParentFile)
      IO.write(configFile, content)
      log.info(s"Created resource-config.json with migration resource pattern")
    }
  }
}

/** Utilities for deriving the manifest object's fully-qualified class name from its file path,
  * and for rendering the initial manifest Scala source from a class name.
  */
private object ManifestNaming {

  /** Derives a fully-qualified class name from the manifest file path relative to the Scala source root.
    *
    * For example, `src/main/scala/com/example/Nomad.scala` yields `com.example.Nomad`.
    */
  def classNameFromFile(manifestFile: File, scalaSourceRoot: File): String = {
    IO.relativize(scalaSourceRoot, manifestFile) match {
      case Some(relativePath) =>
        relativePath.stripSuffix(".scala").split('/').mkString(".")
      case None =>
        manifestFile.base
    }
  }

  /** Generates the Scala source code for a fresh migration manifest with the given class name. */
  def renderManifestSource(className: String): String = {
    val parts = className.split('.').toVector.filter(_.nonEmpty)
    val objectName = parts.lastOption.getOrElse("Nomad")
    val packageDecl = parts.dropRight(1) match {
      case Vector() => ""
      case pkg      => s"package ${pkg.mkString(".")}\n\n"
    }

    s"""|${packageDecl}import nomad.{Migration, NomadMigrations, SupportedDatabase}
        |import javax.sql.DataSource
        |
        |object $objectName extends NomadMigrations {
        |  def database: SupportedDatabase = {
        |    ???
        |  }
        |
        |  // This datasource is used by sbt tasks (nomadMigrate, nomadStatus).
        |  // If you use Migrator directly from code, you can pass a different datasource there.
        |  def datasource: DataSource = {
        |    ???
        |  }
        |
        |  // Your migrations are automatically added here when you run nomadCreate,
        |  // only edit this file to solve conflicts.
        |  def migrations: Vector[Migration] = Vector(
        |  )
        |}
        |""".stripMargin
  }
}

/** Interactive prompting helpers for sbt tasks that require user input (e.g., Flyway import confirmation). */
private object Prompting {

  /** Reads a line of input from the user via sbt's interaction service. */
  def readLine(interaction: InteractionService, prompt: String): String =
    interaction.readLine(prompt, false).getOrElse("")

  /** Prompts the user for a yes/no confirmation, returning the default if input is empty or unrecognized. */
  def confirm(interaction: InteractionService, prompt: String, default: Boolean): Boolean = {
    val input = readLine(interaction, prompt).trim.toLowerCase
    input match {
      case ""          => default
      case "y" | "yes" => true
      case "n" | "no"  => false
      case _           => default
    }
  }
}

/** sbt AutoPlugin that provides migration management tasks and settings.
  *
  * Automatically activated for all JVM projects. Provides tasks for creating, running,
  * and inspecting migrations, as well as importing from Flyway. Uses a child-first classloader
  * to execute user-defined migrations in the project's Scala 3 runtime, isolated from
  * sbt's own Scala 2.12 classpath.
  */
object NomadPlugin extends AutoPlugin {

  override def trigger = allRequirements
  override def requires = plugins.JvmPlugin

  object autoImport {
    val nomadInit = taskKey[Unit]("Create the migration manifest file")
    val nomadMigrate = taskKey[Unit]("Run pending database migrations")
    val nomadStatus = taskKey[Unit]("Show the status of database migrations")
    val nomadCreate = inputKey[Unit]("Create a new migration file")
    val nomadMigrationsDir = settingKey[File]("Directory for migration files")
    val nomadStampFormat = settingKey[String]("Timestamp format for migration file names")
    val nomadManifestFile = settingKey[File]("Path to the Scala manifest file defining migration order")
    val nomadManifestClass = settingKey[String]("Fully qualified class name of the NomadMigrations implementation")
    val nomadHistoryTable = settingKey[String]("Name of the database table used to track applied migrations")
    val nomadSchema = settingKey[String]("Database schema used for migrations and history tracking")
    val nomadAutoCreateSchema = settingKey[Boolean]("Create the configured schema via CREATE SCHEMA IF NOT EXISTS before migrate / cleanAndMigrate. Set to false for least-privilege roles.")
    val nomadGraalSync = settingKey[Boolean]("Automatically sync migration resources to GraalVM native-image resource-config.json")
    val nomadGraalResourceConfigFile = settingKey[File]("Path to the GraalVM resource-config.json file")
    val nomadImportFlyway = taskKey[Unit]("Import Flyway versioned migrations into the Nomad manifest")
  }

  import autoImport._

  override def projectSettings: Seq[Setting[_]] = Seq(
    nomadMigrationsDir := (Compile / resourceDirectory).value / "migrations",
    nomadStampFormat := "yyyyMMddHHmm",
    nomadManifestFile := (Compile / scalaSource).value / "Nomad.scala",
    nomadManifestClass := ManifestNaming.classNameFromFile(nomadManifestFile.value, (Compile / scalaSource).value),
    nomadHistoryTable := "nomad_migrations",
    nomadSchema := "public",
    nomadAutoCreateSchema := true,
    nomadGraalSync := false,
    nomadGraalResourceConfigFile := (Compile / resourceDirectory).value / "META-INF" / "native-image" / "resource-config.json",
    nomadInit / aggregate := false,
    nomadMigrate / aggregate := false,
    nomadStatus / aggregate := false,
    nomadCreate / aggregate := false,
    nomadImportFlyway / aggregate := false,
    nomadInit := {
      val log = streams.value.log
      val manifest = nomadManifestFile.value
      if (manifest.exists()) {
        log.error(s"Manifest file already exists: ${manifest.relativeTo(baseDirectory.value).getOrElse(manifest)}")
        throw new MessageOnlyException("Manifest file already exists. Delete it first if you want to re-initialize.")
      }
      val content = ManifestNaming.renderManifestSource(nomadManifestClass.value)
      IO.createDirectory(manifest.getParentFile)
      IO.write(manifest, content)
      log.info(s"Created manifest: ${manifest.relativeTo(baseDirectory.value).getOrElse(manifest)}")
    },
    nomadMigrate := {
      val log = streams.value.log
      val cp = (Compile / fullClasspath).value.files
      val className = nomadManifestClass.value
      val table = nomadHistoryTable.value
      val schema = nomadSchema.value
      val autoCreateSchema = nomadAutoCreateSchema.value

      val loader = new ChildFirstClassLoader(
        cp.map(_.toURI.toURL).toArray,
        getClass.getClassLoader
      )

      try {
        val manifestClass = loader.loadClass(className + "$")
        val instance = manifestClass.getField("MODULE$").get(null)
        val migrationsMethod = manifestClass.getMethod("migrations")
        val datasourceMethod = manifestClass.getMethod("datasource")
        val databaseMethod = manifestClass.getMethod("database")

        val migrations = migrationsMethod.invoke(instance)
        val datasource = datasourceMethod.invoke(instance)
        val database = databaseMethod.invoke(instance)

        val migratorClass = loader.loadClass("nomad.Migrator")
        val constructor = migratorClass.getConstructors.maxBy(_.getParameterCount)
        val migrator = constructor.newInstance(datasource, database, migrations, table, schema, java.lang.Boolean.valueOf(autoCreateSchema))
        val migrateMethod = migratorClass.getMethod("migrate")
        migrateMethod.invoke(migrator)
      } finally {
        loader.close()
      }

      // Sync GraalVM resource-config.json if enabled
      if (nomadGraalSync.value) {
        val migrationsSubdir = IO.relativize(
          (Compile / resourceDirectory).value,
          nomadMigrationsDir.value
        ).getOrElse("migrations")
        GraalSync.syncResourceConfig(nomadGraalResourceConfigFile.value, migrationsSubdir, log)
      }
    },
    nomadStatus := {
      val log = streams.value.log
      val cp = (Compile / fullClasspath).value.files
      val className = nomadManifestClass.value
      val table = nomadHistoryTable.value
      val schema = nomadSchema.value
      val autoCreateSchema = nomadAutoCreateSchema.value

      val loader = new ChildFirstClassLoader(
        cp.map(_.toURI.toURL).toArray,
        getClass.getClassLoader
      )

      try {
        val manifestClass = loader.loadClass(className + "$")
        val instance = manifestClass.getField("MODULE$").get(null)
        val migrationsMethod = manifestClass.getMethod("migrations")
        val datasourceMethod = manifestClass.getMethod("datasource")
        val databaseMethod = manifestClass.getMethod("database")

        val migrations = migrationsMethod.invoke(instance)
        val datasource = datasourceMethod.invoke(instance)
        val database = databaseMethod.invoke(instance)

        val migratorClass = loader.loadClass("nomad.Migrator")
        val constructor = migratorClass.getConstructors.maxBy(_.getParameterCount)
        val migrator = constructor.newInstance(datasource, database, migrations, table, schema, java.lang.Boolean.valueOf(autoCreateSchema))
        val printStatusMethod = migratorClass.getMethod("printStatus")
        val hasProblems = printStatusMethod.invoke(migrator).asInstanceOf[Boolean]

        if (hasProblems) {
          throw new MessageOnlyException("Migration problems detected.")
        }
      } finally {
        loader.close()
      }
    },
    nomadCreate := {
      val log = streams.value.log
      val interaction = interactionService.value
      val dir = nomadMigrationsDir.value
      val manifest = nomadManifestFile.value
      val args = spaceDelimited("<description>").parsed.mkString
      val description = if (args.nonEmpty) args
        else {
          Prompting.readLine(interaction, "Migration description (leave empty to skip): ").trim
        }
      val timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern(nomadStampFormat.value))
      val fileName = if (description.nonEmpty) s"M${timestamp}_$description.sql" else s"M$timestamp.sql"
      val file = dir / fileName
      IO.createDirectory(dir)
      IO.write(file, "")
      log.info(s"Created migration: ${file.relativeTo(baseDirectory.value).getOrElse(file)}")

      // Auto-edit the manifest file to add the new migration
      val migrationsSubdir = IO.relativize(
        (Compile / resourceDirectory).value,
        dir
      ).getOrElse("migrations")
      val resourcePath = s"$migrationsSubdir/$fileName"
      if (manifest.exists()) {
        val content = IO.read(manifest)
        ManifestEditor.addSqlMigrations(content, Seq(resourcePath)) match {
          case Right(updated) =>
            IO.write(manifest, updated)
            log.info(s"Added migration to manifest: ${manifest.relativeTo(baseDirectory.value).getOrElse(manifest)}")
          case Left(message) =>
            log.warn(message)
        }
      } else {
        log.warn(s"Manifest file not found: ${manifest.relativeTo(baseDirectory.value).getOrElse(manifest)}")
        log.warn("Please add the migration to your manifest manually.")
      }

      // Sync GraalVM resource-config.json if enabled
      if (nomadGraalSync.value) {
        GraalSync.syncResourceConfig(nomadGraalResourceConfigFile.value, migrationsSubdir, log)
      }
    },
    nomadImportFlyway := {
      val log = streams.value.log
      val interaction = interactionService.value
      val manifest = nomadManifestFile.value
      val resourceDir = (Compile / resourceDirectory).value
      val cp = (Compile / fullClasspath).value.files
      val className = nomadManifestClass.value
      val table = nomadHistoryTable.value
      val schema = nomadSchema.value
      val autoCreateSchema = nomadAutoCreateSchema.value
      val base = baseDirectory.value

      if (!manifest.exists()) {
        throw new MessageOnlyException("Manifest file not found. Run nomadInit first.")
      }

      // Scan resource directory recursively for Flyway versioned migrations
      val flywayPattern = """^V(\d+(?:\.\d+)*)(?:__.*)?\.sql$""".r
      val allSqlFiles = if (resourceDir.exists()) {
        resourceDir.**(GlobFilter("V*.sql")).get
      } else Vector.empty

      val flywayMigrations = allSqlFiles.flatMap { file =>
        val name = file.getName
        flywayPattern.findFirstMatchIn(name).map { m =>
          val versionStr = m.group(1)
          val versionParts = versionStr.split('.').map(_.toLong).toVector
          val resourcePath = IO.relativize(resourceDir, file).getOrElse(file.getName)
          (versionParts, resourcePath)
        }
      }

      if (flywayMigrations.isEmpty) {
        log.warn("No Flyway versioned migrations (V*__*.sql) found in resource directories.")
      } else {
        // Sort by Flyway version order (numeric comparison per segment)
        val sorted = flywayMigrations.sortWith { case ((v1, _), (v2, _)) =>
          val pairs = v1.zipAll(v2, 0L, 0L)
          val cmp = pairs.collectFirst { case (a, b) if a != b => a < b }
          cmp.getOrElse(false)
        }

        // Read manifest and find which resource paths are already listed
        val content = IO.read(manifest)
        val alreadyListed = sorted.filter { case (_, path) => content.contains(s""""$path"""") }
        val toAdd = sorted.filterNot { case (_, path) => content.contains(s""""$path"""") }

        if (toAdd.isEmpty) {
          log.info("All Flyway migrations are already in the manifest.")
        } else {
          ManifestEditor.addSqlMigrations(content, toAdd.map(_._2)) match {
            case Right(updated) =>
              IO.write(manifest, updated)

              for ((_, path) <- toAdd) {
                log.info(s"Imported: $path")
              }
              log.info(s"Added ${toAdd.size} Flyway migration(s) to manifest.")
              if (alreadyListed.nonEmpty) {
                log.info(s"Skipped ${alreadyListed.size} migration(s) already in manifest.")
              }
            case Left(message) =>
              log.warn(message)
          }
        }

        // Offer to import Flyway schema history
        val allPaths = sorted.map(_._2)
        val manifestName = manifest.relativeTo(base).getOrElse(manifest)
        val shouldImportHistory = Prompting.confirm(
          interaction,
          s"Would you like to import your Flyway schema history into Nomad? The datasource provided by $manifestName will be used. Only SQL migrations will be imported. [y/n]: ",
          default = false
        )
        if (shouldImportHistory) {
          val flywayTableInput = Prompting.readLine(
            interaction,
            "Confirm Flyway history table (ENTER for default: flyway_schema_history): "
          )
          val flywayTable = if (flywayTableInput.trim.isEmpty) "flyway_schema_history"
            else flywayTableInput.trim

          val loader = new ChildFirstClassLoader(
            cp.map(_.toURI.toURL).toArray,
            getClass.getClassLoader
          )

          try {
            val manifestClass = loader.loadClass(className + "$")
            val instance = manifestClass.getField("MODULE$").get(null)
            val datasourceMethod = manifestClass.getMethod("datasource")
            val databaseMethod = manifestClass.getMethod("database")
            val migrationsMethod = manifestClass.getMethod("migrations")

            val datasource = datasourceMethod.invoke(instance)
            val database = databaseMethod.invoke(instance)
            val migrations = migrationsMethod.invoke(instance)

            val migratorClass = loader.loadClass("nomad.Migrator")
            val constructor = migratorClass.getConstructors.maxBy(_.getParameterCount)
            val migrator = constructor.newInstance(datasource, database, migrations, table, schema, java.lang.Boolean.valueOf(autoCreateSchema))
            val analyzeMethod = migratorClass.getMethod("analyzeFlywayHistoryImport", classOf[String], classOf[Array[String]])
            val analysis = analyzeMethod.invoke(migrator, flywayTable, allPaths.toArray)

            val remappableMismatchCount = analysis.getClass
              .getMethod("remappableMismatchCount")
              .invoke(analysis)
              .asInstanceOf[Int]
            val missingCount = analysis.getClass
              .getMethod("missingCount")
              .invoke(analysis)
              .asInstanceOf[Int]
            val ambiguousCount = analysis.getClass
              .getMethod("ambiguousCount")
              .invoke(analysis)
              .asInstanceOf[Int]

            val shouldRemap =
              if (remappableMismatchCount > 0) {
                if (missingCount > 0 || ambiguousCount > 0) {
                  log.warn(
                    s"Detected $remappableMismatchCount Flyway script path mismatch(es), plus $missingCount missing and $ambiguousCount ambiguous script match(es)."
                  )
                }

                Prompting.confirm(
                  interaction,
                  "Script paths for your migrations do not match what is stored in flyway schema history. Would you like to still import the scripts with their current paths in this project? [Y/n]: ",
                  default = true
                )
              } else {
                false
              }

            if (remappableMismatchCount > 0 && !shouldRemap) {
              log.info("Canceled Flyway history import after script path mismatch confirmation.")
            } else {
              val importMethod = migratorClass.getMethod(
                "importFlywayHistory",
                classOf[String],
                classOf[Array[String]],
                java.lang.Boolean.TYPE
              )
              val _ = importMethod.invoke(migrator, flywayTable, allPaths.toArray, java.lang.Boolean.valueOf(shouldRemap))
            }
          } finally {
            loader.close()
          }
        }
      }
    }
  )
}
